### ISSUE TITLE
This repository is empty?

### ISSUE THREAD

**Issue by phadej** [strake/mtl-tf.hs#1]
Is it the place for `mtl-tf`, https://hackage.haskell.org/package/mtl-tf?

It doesnt' compile with GHC-7.8:

```
Control/Monad/Error/Class.hs:104:11:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Prelude)
```
